# Generated by Django 3.2 on 2022-11-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicname', models.CharField(help_text="Enter the author's Steam profile name", max_length=255)),
                ('profile_url', models.URLField()),
                ('avatar', models.URLField()),
                ('number_of_followers', models.IntegerField()),
                ('workshop_submissions', models.IntegerField()),
                ('coop_maps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicname', models.CharField(max_length=255)),
                ('profile_url', models.CharField(max_length=2083)),
                ('avatar', models.CharField(max_length=2083)),
                ('number_of_followers', models.IntegerField()),
                ('workshop_submissions', models.IntegerField()),
                ('coop_maps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoGroupAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SteamGroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Steamid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['nicname', '-number_of_followers'], name='authors_aut_nicname_c103e4_idx'),
        ),
    ]
