# Generated by Django 3.2 on 2021-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicname', models.CharField(max_length=255)),
                ('realname', models.CharField(max_length=255)),
                ('profile_url', models.CharField(max_length=2083)),
                ('steam_level', models.IntegerField()),
                ('avatar', models.CharField(max_length=2083)),
                ('loc_country_code', models.CharField(max_length=10)),
                ('number_of_followers', models.IntegerField()),
                ('workshop_submissions', models.IntegerField()),
            ],
        ),
    ]
