# Generated by Django 3.2 on 2021-04-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_remove_author_realname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SteamId',
        ),
        migrations.RemoveField(
            model_name='author',
            name='steam_level',
        ),
        migrations.AlterField(
            model_name='author',
            name='loc_country_code',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
