# Generated by Django 3.2 on 2021-04-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20210418_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='loc_country_code',
        ),
        migrations.AddField(
            model_name='author',
            name='coop_maps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
