# Generated by Django 3.2 on 2021-04-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_auto_20210428_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steamid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(max_length=30)),
            ],
        ),
    ]
