# Generated by Django 3.2 on 2021-05-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_steamgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SteamGroup',
            new_name='SteamGroupName',
        ),
    ]
