# Generated by Django 3.2 on 2021-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_nogroupauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
