# Generated by Django 3.2 on 2021-05-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_updatedate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-number_of_followers', 'id']},
        ),
    ]
