# Generated by Django 3.2 on 2021-05-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
