# Generated by Django 3.2 on 2021-05-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0013_alter_author_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nicname',
            field=models.CharField(help_text="Enter the author's Steam profile name", max_length=255),
        ),
    ]
