# Generated by Django 3.2 on 2021-06-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0015_auto_20210530_1751'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['nicname', '-number_of_followers'], name='authors_aut_nicname_c103e4_idx'),
        ),
    ]
